import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatDistanceToNowStrict } from "date-fns";
import { RefreshCw, Clock } from "lucide-react";
import { cn } from "../lib/utils";
import { ModeToggle } from "./mode-toggle";
import { Button } from "./ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
export function Layout({ title, description, lastUpdated, refreshing, onRefresh, formSlot, listSlot, pendingCount = 0 }) {
    const lastUpdatedText = lastUpdated && formatDistanceToNowStrict(new Date(lastUpdated), { addSuffix: true });
    return (_jsx("div", { className: cn("min-h-screen bg-gradient-to-b from-background via-background/95 to-background", "text-foreground"), children: _jsxs("div", { className: "container flex min-h-screen flex-col gap-8 py-10", children: [_jsxs("header", { className: "flex flex-col gap-4 md:flex-row md:items-center md:justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-semibold tracking-tight", children: title }), description && (_jsxs("p", { className: "text-muted-foreground", children: [description, lastUpdatedText && (_jsxs("span", { className: "ml-2 inline-flex items-center gap-1 text-sm text-muted-foreground", children: [_jsx("span", { className: "h-1.5 w-1.5 rounded-full bg-emerald-500" }), "Updated ", lastUpdatedText] }))] }))] }), _jsxs("div", { className: "flex items-center gap-2", children: [typeof pendingCount === "number" && pendingCount > 0 && (_jsxs("span", { className: "inline-flex items-center gap-2 rounded-full border border-amber-300/60 bg-amber-100/80 px-4 py-2 text-xs font-medium text-amber-900 shadow-sm dark:border-amber-500/40 dark:bg-amber-500/10 dark:text-amber-200", children: [_jsx(Clock, { className: "h-3.5 w-3.5" }), _jsxs("span", { children: [pendingCount, " pending"] })] })), onRefresh && (_jsxs(Button, { variant: "outline", onClick: onRefresh, disabled: refreshing, children: [_jsx(RefreshCw, { className: cn("mr-2 h-4 w-4", refreshing && "animate-spin") }), "Refresh"] })), _jsx(ModeToggle, {})] })] }), _jsxs("main", { className: "grid gap-6 lg:grid-cols-[380px_1fr] lg:items-start", children: [_jsxs(Card, { className: "border-dashed border-primary/30 bg-card/60 backdrop-blur", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Send Transaction" }), _jsx(CardDescription, { children: "Provide mnemonic, recipient address, amount, and optional note to submit an Algorand payment." })] }), _jsx(CardContent, { children: formSlot })] }), _jsxs(Card, { className: "border-dashed border-primary/30 bg-card/60 backdrop-blur", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Recent Transactions" }), _jsx(CardDescription, { children: "Latest entries retrieved from the backend." })] }), _jsx(CardContent, { children: listSlot })] })] })] }) }));
}
