import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatDistanceToNow, format } from "date-fns";
import { BadgeCheck, Clock, Loader2 } from "lucide-react";
import { cn } from "../lib/utils";
const statusStyles = {
    pending: "bg-amber-200 text-amber-900 dark:bg-amber-500/20 dark:text-amber-200",
    confirmed: "bg-emerald-200 text-emerald-900 dark:bg-emerald-500/20 dark:text-emerald-100",
    failed: "bg-rose-200 text-rose-900 dark:bg-rose-500/20 dark:text-rose-100"
};
export function TransactionList({ transactions }) {
    if (!transactions.length) {
        return (_jsxs("div", { className: "flex flex-col items-center justify-center gap-3 rounded-lg border border-dashed p-8 text-center text-muted-foreground", children: [_jsx(Clock, { className: "h-6 w-6" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-foreground", children: "No transactions yet" }), _jsx("p", { className: "text-sm", children: "Send your first transaction to see it listed here." })] })] }));
    }
    return (_jsx("div", { className: "space-y-4", children: transactions.map((txn) => (_jsxs("article", { className: "rounded-lg border bg-gradient-to-br from-background/70 via-background to-background p-4 shadow-sm", children: [_jsxs("header", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm font-mono", children: [_jsx("span", { className: "font-semibold", children: "TX:" }), _jsx("span", { className: "truncate max-w-[16rem]", children: txn.txId })] }), _jsxs("span", { className: cn("inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-medium uppercase tracking-wide", statusStyles[txn.status]), children: [txn.status === "pending" && _jsx(Loader2, { className: "h-3.5 w-3.5 animate-spin" }), txn.status === "confirmed" && _jsx(BadgeCheck, { className: "h-3.5 w-3.5" }), txn.status] })] }), _jsxs("dl", { className: "mt-3 grid gap-2 text-sm", children: [_jsxs("div", { className: "grid gap-1", children: [_jsx("dt", { className: "text-muted-foreground", children: "From" }), _jsx("dd", { className: "truncate font-mono text-xs md:text-sm", children: txn.from })] }), _jsxs("div", { className: "grid gap-1", children: [_jsx("dt", { className: "text-muted-foreground", children: "To" }), _jsx("dd", { className: "truncate font-mono text-xs md:text-sm", children: txn.to })] }), _jsxs("div", { className: "grid gap-1", children: [_jsx("dt", { className: "text-muted-foreground", children: "Amount" }), _jsxs("dd", { className: "font-semibold", children: [txn.amount, " ALGO"] })] }), txn.note && (_jsxs("div", { className: "grid gap-1", children: [_jsx("dt", { className: "text-muted-foreground", children: "Note" }), _jsx("dd", { className: "rounded-md bg-muted px-3 py-2 text-xs text-muted-foreground", children: txn.note })] })), _jsxs("div", { className: "grid gap-1", children: [_jsx("dt", { className: "text-muted-foreground", children: "Created" }), _jsxs("dd", { className: "text-xs", children: [format(new Date(txn.createdAt), "PPpp"), " \u00B7", " ", formatDistanceToNow(new Date(txn.createdAt), { addSuffix: true })] })] }), txn.confirmedRound && (_jsxs("div", { className: "grid gap-1", children: [_jsx("dt", { className: "text-muted-foreground", children: "Confirmed round" }), _jsx("dd", { className: "font-mono text-xs", children: txn.confirmedRound })] }))] })] }, txn._id ?? txn.txId))) }));
}
